services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_authentication
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5436:5432"